language: r
r: bioc-devel
cache: packages
dist: trusty
sudo: required

warnings_are_errors: true

apt_packages:
  - qpdf
  
script:
  - R CMD build . ${R_BUILD_ARGS}
  - export PKG_TARBALL=`ls -1t *.tar.gz | head -n 1`
  - R CMD check ${PKG_TARBALL} ${R_CHECK_ARGS}

notifications:
  email: false

matrix:
  include:
  - r: bioc-devel  
  - r: bioc-release
    
    after_success:
      - R CMD INSTALL ${PKG_TARBALL}
      - Rscript -e 'install.packages("pkgdown")'
      - Rscript -e 'pkgdown::build_site()'
      - mv docs ..
      - rm -r *
      - mv ../docs/* .
      
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_API_TOKEN
      on:
        branch: master
        target_branch: gh-pages
  
env:
   global:
     - R_BUILD_ARGS=""
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran --compact-vignettes=gs+qpdf"

cran: http://cran.rstudio.com
